version: '3.4'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/appligo/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
  db:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  gem_cache:
  db_data:
  node_modules:
